In [1]:
import torch
import torch.nn as nn
from torch.optim import SGD
from numpy import *
import matplotlib.pyplot as plt
import math
from tqdm import tqdm
plt.style.use(['science','notebook','grid'])
params = {'mathtext.default': 'regular' }          
plt.rcParams.update(params)

In [2]:
vals = load(r"C:\Users\Nunocastanheira\Desktop\boooks\research\Gelb!\Code\SESSA-Project-main\output\Master.npy")

In [3]:
energy = torch.tensor(vals[0,0,:,0],dtype=torch.float)
thickness = torch.tensor(range(1,25),dtype=torch.float)
counts = torch.tensor(vals[0,:,:,1],dtype=torch.float)
test = torch.tensor(vals[0,:,:,1],dtype=torch.float)*10**7
print(shape(energy))
print(shape(test))
print(shape(thickness))
print(energy)
print(test)

torch.Size([2048])
torch.Size([24, 2048])
torch.Size([24])
tensor([ 500.0000,  500.4880,  500.9770,  ..., 1498.5400, 1499.0200,
        1499.5100])
tensor([[2.9532, 2.9536, 2.9540,  ..., 0.0036, 0.0036, 0.0036],
        [2.9545, 2.9549, 2.9553,  ..., 0.0037, 0.0037, 0.0037],
        [2.9357, 2.9361, 2.9365,  ..., 0.0038, 0.0038, 0.0038],
        ...,
        [2.9114, 2.9118, 2.9122,  ..., 0.0047, 0.0047, 0.0046],
        [2.8748, 2.8752, 2.8755,  ..., 0.0047, 0.0047, 0.0047],
        [2.9147, 2.9151, 2.9154,  ..., 0.0048, 0.0047, 0.0047]])


In [4]:
def train_model(x,y,f, n_epochs=500):
    opt = SGD(f.parameters(), lr=10**-5)
    L = nn.KLDivLoss(reduction = 'batchmean')

    # Train model
    losses = []
    for _ in tqdm(range(n_epochs)):
        opt.zero_grad() 
        loss_value = L(f(x), y)
        loss_value.backward() 
        opt.step() 
        losses.append(loss_value.item())
    return f, losses

class MyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.Matrix1 = nn.Linear(2048,2**13)
        self.Matrix2 = nn.Linear(2**13,2**13)
        self.Matrix3 = nn.Linear(2**13,1)
        self.R = nn.ReLU()
    def forward(self,x):
        x = self.R(self.Matrix1(x))
        x = self.R(self.Matrix2(x))
        x = self.Matrix3(x)
        return x.squeeze()

x = test
y = thickness
f = MyNeuralNet()

# Train model
f, losses = train_model(x,y,f, n_epochs=5000)

100%|██████████| 5000/5000 [48:13<00:00,  1.73it/s] 


In [5]:
shape(f(x))

torch.Size([24])

In [6]:
f(x)

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       grad_fn=<SqueezeBackward0>)

In [7]:
thickness

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [ ]:
plt.plot(losses[4900:])
plt.xlabel("epoch")
plt.ylabel("Loss")
plt.show()